### PR TITLE
Fixed building error due to recent Brasilian translation update.

### PR DESCRIPTION
**Pull request by ArthurBorsboom**
The update was submitted in ISO-8859-1 format which is a not
allowed format. The correct format is UTF-8. This commit has
converted the translation to UTF-8.

### CODE REVIEW

**Comment by jleclanche** [comment]
@PCMan this needs to be merged in. I would do it but I don't know if it's safe to do so seeing as github is the mirror and not the main repo. Can you confirm?

**Comment by jleclanche** [comment]
We need a way to safely accept pull requests from github if we're going to keep them open (which would be a good thing, they have a very low barrier of entry and we need contributors).

**Comment by ArthurBorsboom** [comment]
Agreed. I love to help out where I can.

**Pull request closed without merging**
